#!/bin/bash

cd ~/main.ton.dev/tonos-cli/target/release
rm ~/ton-keys/${1}.amount.csv

for i in {1..x};
do
each_raw_addr=$(cat ~/ton-keys/"${1}.raw.csv" | awk "FNR == ${i}")
./tonos-cli account $each_raw_addr | awk "FNR == 8" | tr -d 'balance:'' ' >> ~/ton-keys/${1}.amount.csv
done
